### ISSUE TITLE
[bug] FGK101 binary sensor stopped updating

### ISSUE THREAD

**Issue by paszczaq** [zwave-js/zwave-js#2285] opened 2021-04-09 12:21 UTC
**Checklist:**

- [x] I am using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I am using ZWaveJS2MQTT. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog and my problem was **not** mentioned there.

**Describe the bug**

Fibaro Door/Window FGK101 (v.2.5) sensor doesnt change binary sensor status after update of the Z WaveJS to MQTT
Last working addon version 0.9.0
Non Working after update to 0.9.1 and 0.11.0
Currently non working:

zwavejs2mqtt: 3.2.0
zwave-js: 7.1.1

I did submit bug in https://github.com/home-assistant/core/issues/48790

**Device information**
Device: Fibaro Door/Window FGK101 (v.2.5) 
Device ID: 271-4096-1792 (0x010f-0x0700-0x1000)

Affected Nodes ID: 18, 20, 21, 22

**Did you change anything?**
- [x] **Yes**: *Updating ZWaveJS2MQTT addon from 0.9.0 to 0.11.0*
- [ ] **No**

**Did this use to work before?**
- [ ] **Don't know**, this is a new device
- [ ] **No**, it never worked anywhere
- [x] **Yes**, in: *0.9.0 version of zwavejs2mqtt addon
    
**How are you using `node-zwave-js`**
- [ ] `zwavejs2mqtt` (latest) docker image
- [ ] `zwavejs2mqtt` (dev) docker image
- [ ] `zwavejs2mqtt` Manual Docker build
    - `node-zwave-js` branch: 
    - `zwavejs2mqtt` branch: 
- [ ] ioBroker.zwave2 adapter
- [x] `HomeAssistant` version core-2021.4.1 (Home Assistant OS 5.13)
- [ ] Pkg
- [ ] Manual Docker build
    - `node-zwave-js` branch: 
    - `zwavejs2mqtt` branch: 
- [ ] `node-red-contrib-zwave-js`
    - Module version (double click node): 
- [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github)) 
- [ ] Other: 

**To Reproduce**

1. Update zwavejs2mqtt addon to ver. 0.11
2. Change binary sensor state (eg. open window)
3. No change in HA / ZwaveJS2MQTT panel and devices info - binary sensor doesnt change it state

**Additional context**

**Logfile:**

[zwavejs_356.zip](https://github.com/zwave-js/node-zwave-js/files/6285600/zwavejs_356.zip)

[zwave_js_dump.zip](https://github.com/zwave-js/node-zwave-js/files/6285611/zwave_js_dump.zip)

**Comment by AlCalzone** [comment] 2021-04-09 12:53
Just to verify: Multilevel Sensor still works? At least the logs look like it.

**Comment by paszczaq** [comment] 2021-04-09 13:25
Yes, the Multilevel Sensor works - I have temperature sensor connected there and its working for those 4 devices. Example
node 22: 
![image](https://user-images.githubusercontent.com/2835696/114186550-46885680-9947-11eb-99c6-d8335ee972f2.png)
You can see temperature drops when the door was opened :) - windy weather today :)

**Comment by AlCalzone** [comment] 2021-04-09 13:51
Thanks. Unfortunately, this is a symptom of a much larger issue for which we only had semi-working workarounds so far. Every time we tried to fix something that didn't work, we broke something else. You're going to have to wait for https://github.com/zwave-js/node-zwave-js/issues/2286 to be resolved.

**Comment by AlCalzone** [comment] 2021-04-09 13:51
Duplicate of #2286

**Closed as completed** 2021-04-09 13:51 UTC
Labels: bug

**Comment by capjay1** [comment] 2021-04-09 18:33
Just want to add that the "Vision Security Motion Sensor (ZP3102)" exhibits similar behavior to the Fibaro Door/Window FGK101. Thanks.

**Comment by AlCalzone** [comment] 2021-04-09 22:24
FYI, I've rolled the changes back until #2286 is solved. Should be out later in version 7.2.1

**Comment by bazmk2** [comment] 2021-04-17 19:50
Also just to add that I think Everspring SM103 widow/door sensor exhibits the same behaviour.  Happy ro send more detail if needed

**Comment by AlCalzone** [comment] 2021-04-18 15:12
@bazmk2 please open a new issue and post a log where you actuate the device manually.
