### ISSUE TITLE
No way to check if an interview has stopped after the final "interview failed" event has passed.

### ISSUE THREAD

**Issue by RoboPhred** [zwave-js/zwave-js#1105] opened 2020-11-08 22:13 UTC
Currently, when a node fails its interview, there is no indication to the outside world beyond the "interview failed" event, and interviewStage remains on the failing interview step.  I would like to be able to check if the interview of a node has failed without relying on capturing the event. Adding a "Failed" stage to InterviewStage would be useful in this regard.

My use case is I am trying to add a user-triggerable re-interview for failed nodes using refreshInfo.  The documentation warns to not call it during an interview, but there is no real way to tell when it is safe to call for failed nodes, as the node's interviewStage will be stuck reporting an ongoing interview indefinitely after failure.

**Comment by AlCalzone** [comment] 2020-11-09 07:54
Good point - however the `InterviewStage` is used to remember how far the interview has progressed, so that some steps can be skipped when repeating an interview. Even after a failed interview it is not necessary to repeat all steps - the proposed solution would discard this information.

I've been planning to [rewrite the interview](https://github.com/zwave-js/node-zwave-js/issues/903) process as a whole. My preferred approach will avoid the problem of multiple concurrent interview processes. I'll be adding your requirement of better transparency there and mark this as a duplicate. Feel free to discuss any points regarding the interview process and its shortcomings in #903.

**Comment by AlCalzone** [comment] 2020-11-09 07:57
duplicate of #903

**Closed as completed by AlCalzone** 2020-11-09 07:57 UTC
