### ISSUE TITLE
MCO home MH-C421 multilevel switch is not good

### ISSUE THREAD

**Issue by S1M8N** [zwave-js/zwave-js#2454] opened 2021-04-24 19:44 UTC
**Checklist:**

-   [x] I am using HomeAssistant.
-   [x] I am using ZWaveJS2MQTT.
-   [x] I have checked the troubleshooting section and my problem is **not** described there. Yes and No
-   [x] I have read the changelog and my problem was **not** mentioned there. Yes and No...

**Describe the bug**

Hello,

I use home assistant OS without any add-on except zwavejs2mqtt which is in the latest version and the z-wave js integration that goes with it. However my C421 home MCO switches are not considered a multilevel switch (I think). I can still move them up and down I don't really know how but it works. On the other hand, it is impossible for me to do the STOP / PAUSE action ...

If you need a log please let me know where they are so I can send them to you. If I need an additional add on to retrieve these logs let me know

This is an issue that had already been addressed and corrected by adding a force multilevel switch for my device. When I did not yet have the add-on version it was good the force multievel switch worked but there it does not seem to work or badly ...
I noticed that if the module was in an unknown state everything was working in the management of the multilevel switch however when it is added correctly this is no longer the case and the stop button no longer works ...

I won't go into details because I don't really know how it works.

Hope we can solve this problem.

Thank you in advance

**Device information**

MCO home C421
What are the node IDs?
6 and 8

**Did you change anything?**

-   [ ] **No**

**Did this use to work before?**

-   [ ] **Don't know**

**How are you using `node-zwave-js`**
-   [ ] `HomeAssistant` version 0.13.0

**To Reproduce**

1. Go to 'Zwave js Integration'
2. Click on 'Stop button'
4. See error (doesn't work)
[zwave_js_dump.zip](https://github.com/zwave-js/node-zwave-js/files/6370474/zwave_js_dump.zip)

**Comment by blhoward2** [comment] 2021-04-26 02:58
What do you mean the stop/pause action? Can you go into the zwavejs2mqtt UI, go to that node, and see if everything works when controlling it under the Multilevel sub-tab?

**Comment by AlCalzone** [comment] 2021-04-26 07:54
Also, I'm probably going to need a zwave-js logfile where you control the device.

**Comment by S1M8N** [comment] 2021-04-26 16:51
> Also, I'm probably going to need a zwave-js logfile where you control the device.


[faf58650.zip](https://github.com/zwave-js/node-zwave-js/files/6378748/faf58650.zip)

**Comment by blhoward2** [comment] 2021-04-27 02:22
The log is helpful but can you also answer my questions? We need to understand the issue.

**Comment by AlCalzone** [comment] 2021-04-27 06:40
@S1M8N that's no logfile :(

**Comment by S1M8N** [comment] 2021-04-27 16:35
Yes sorry... I have that :
[Log and printscreen.zip](https://github.com/zwave-js/node-zwave-js/files/6386153/Log.and.printscreen.zip)

**Comment by AlCalzone** [comment] 2021-04-27 16:41
Thanks, but we still need a bit of explanation what the problem is. In your log I see that you control the device using `Multilevel Switch CC` and it changes the value.

**Comment by S1M8N** [comment] 2021-04-27 16:54
Yes, however the pause button does not work : 
![image](https://user-images.githubusercontent.com/75216525/116281473-0bc94f80-a78a-11eb-941b-0268c7e4063b.png)

**Comment by AlCalzone** [comment] 2021-04-27 19:01
That's in Home Assistant though. I'd need to see a log where you push that, but I don't know how to get a log out of HA.

**Comment by S1M8N** [comment] 2021-04-27 19:03
I understand but if I do not go through HA I do not have the pause button that appears in the add on zwavejs2mqtt. Moreover if I do not understand but I only have the possibility of doing UP / DOWN from HA in the add on I can only manage the position

**Comment by AlCalzone** [comment] 2021-04-27 20:07
@S1M8N your cache file above contains `version: 0` for `Multilevel Switch` on both nodes. Either the node didn't respond during the interview, or your cache file got corrupted.
Please re-interview both nodes in `zwavejs2mqtt` (under the "advanced" node options) and post a log of that. Maybe that fixes the problem - if not, I'll at least know why.

**Comment by S1M8N** [comment] 2021-04-27 20:31
it doesn't seem to have helped. Even worse ...
However once I added the module and I had an unknown state and everything worked ... But when I have everything correct at Device ID level the problem is the one mentioned above .... 
[Re-interview_log.zip](https://github.com/zwave-js/node-zwave-js/files/6387493/Re-interview_log.zip)

**Comment by AlCalzone** [comment] 2021-04-27 20:38
Okay, the node is contradicting itself. First it lists Multilevel Switch as supported, then it claims it does not support Multilevel Switch:
```
2021-04-27T20:24:05.603Z CNTRLR « [Node 006] node info received
                                  supported CCs:
                                  · [...]
                                  · Multilevel Switch
...
2021-04-27T20:24:05.967Z DRIVER « [Node 006] [REQ] [ApplicationCommand]
                                  └─[VersionCCCommandClassReport]
                                      CC:      Multilevel Switch
                                      version: 0
2021-04-27T20:24:05.974Z CNTRLR   [Node 006]   does NOT support CC Multilevel Switch (0x26)
```

We can force-override this information via the config files, but I'm not sure which version it actually supports. Going with 1 probably doesn't hurt.

**Comment by AlCalzone** [comment] 2021-04-27 20:49
Ok, it turns out we already forced it to support `Multilevel Switch`, but that was not enough.

**Comment by S1M8N** [comment] 2021-05-01 13:49
@AlCalzone, 

Your changes had no effect

I have included the module again and check that the config file has been changed... 
[logs.zip](https://github.com/zwave-js/node-zwave-js/files/6409660/logs.zip)

**Comment by AlCalzone** [comment] 2021-05-05 14:43
@S1M8N you have to re-interview it for the changes to be applied.

**Comment by S1M8N** [comment] 2021-05-05 14:46
> @S1M8N you have to re-interview it for the changes to be applied.

@AlCalzone, Yes I have make that...

**Comment by S1M8N** [comment] 2021-05-12 13:41
Hello @AlCalzone, 

I'm sorry but I don't have an answer, were you able to find something or do you need something more ??

thank you for your work

**Comment by AlCalzone** [comment] 2021-05-12 16:21
Please re-interview the device and share the zwave-js log and the cache files `<homeid>.json` and `<homeid>.values.json` afterwards.

**Comment by S1M8N** [comment] 2021-05-12 16:55
> Please re-interview the device and share the zwave-js log and the cache files `<homeid>.json` and `<homeid>.values.json` afterwards.

Ok, I have re-interview the devices. It's the node 10

**Comment by S1M8N** [comment] 2021-05-15 14:12
@AlCalzone,

The logs is ok for you ?
[Logs (1).zip](https://github.com/zwave-js/node-zwave-js/files/6487550/Logs.1.zip)

**Comment by AlCalzone** [comment] 2021-05-16 16:43
Ok I think I found it. The change does get applied and you can even see in the cache now that the version is forced to be `1`:
```json
                "0x26": {
                    "name": "Multilevel Switch",
                    "endpoints": {
                        "0": {
                            "isSupported": true,
                            "isControlled": false,
                            "secure": false,
                            "version": 1
                        }
                    }
                },
```

However, the interview for that CC is still not done, which is why you're not seeing those values.

**Comment by S1M8N** [comment] 2021-05-16 16:55
ok can you do something about it?

**Comment by AlCalzone** [comment] 2021-05-16 16:57
Yeah

**Comment by AlCalzone** [comment] 2021-05-16 16:58
Duplicate of #2273

Please follow that issue for an update

**Closed as completed by AlCalzone** 2021-05-16 16:58 UTC
Labels: bug

**Comment by S1M8N** [comment] 2021-05-28 19:15
@AlCalzone
Hello, I still cannot use the stop button on my shutter. I have version 7.7.0 of z-wavejs and the latest version of the plugin. I re included the device. Its node is now 12.
[Log 28.02.2021.zip](https://github.com/zwave-js/node-zwave-js/files/6562912/Log.28.02.2021.zip)

**Comment by AlCalzone** [comment] 2021-05-28 20:02
The issue I linked to isn't done yet.

**Comment by S1M8N** [comment] 2021-05-29 12:22
> The issue I linked to isn't done yet.

Ok when are you planning to do this?

**Comment by S1M8N** [comment] 2021-06-01 18:11
> The issue I linked to isn't done yet.

@AlCalzone
Ok when are you planning to do this?

**Comment by AlCalzone** [comment] 2021-06-01 20:28
I can't make any promises right now. Will do it soon, but that's about as concrete as I can be at the moment.

**Comment by S1M8N** [comment] 2021-06-01 20:30
> I can't make any promises right now. Will do it soon, but that's about as concrete as I can be at the moment.

I hope you will have time before the end of June it would be super cool
