### ISSUE TITLE
Issue with Greenwave PowerNode 6 on first port

### ISSUE THREAD

**Issue by Aohzan** [zwave-js/zwave-js#2973] opened 2021-07-03 19:53 UTC
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
Try to turn on the port 1

What do you observe?
Port 1 status report that it is already on but no power on the outlet. I have to turn it off and on directly again

What did you expect to happen?
Port 1 status is off, and I can turn it on

Watch the switch entity of the first outlet

### Device information

Manufacturer:  GreenWave
Model name: PowerNode 6
Node ID in your network: 16

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version: 0.1.28
Z-Wave JS 7.10.0
Z-Wave JS Server 1.8.0

### Did you change anything?

yes (please describe)

### If yes, what did you change?

Update to 7.7.4 or 7.9.0, I don't know on which version it started to bug

### Did this work before?

Yes (please describe)

### If yes, where did it work?

Ok with version before

### Attach Driver Logfile

```
2021-07-03T19:45:50.194Z CNTRLR   [Node 016] Timed out while waiting for a response from the node
2021-07-03T19:45:50.236Z CNTRLR   [Node 016] Mapping unsolicited report from root device to first supporting end
                                  point #1
```

**Comment by Aohzan** [comment] 2021-07-03 20:15
When I turn off outlet 2->6, the status of outlet 1 become off, but the outlet is still on.
So I turn on and off the switch of outlet 1, and 10-15s later, the outlet turn really off.
The log :
```
2021-07-03T20:12:37.242Z SERIAL « 0x01180004001012600d010632022134000002180009000001e25e              (26 bytes)
2021-07-03T20:12:37.244Z CNTRLR   [Node 016] [~] [Meter] value[66049]: 48.2 => 53.6                 [Endpoint 6]
2021-07-03T20:12:37.244Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:12:37.246Z DRIVER « [Node 016] [REQ] [ApplicationCommand]
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      6
                                    │ destination: 0
                                    └─[MeterCCReport]
                                        type:        Electric
                                        scale:       W
                                        rate type:   Consumed
                                        value:       53.6
                                        time delta:  9 seconds
                                        prev. value: 48.2
2021-07-03T20:12:38.741Z SERIAL « 0x01180004001012600d01013202213400000023000900000036b5              (26 bytes)
2021-07-03T20:12:38.743Z CNTRLR   [Node 016] [~] [Meter] value[66049]: 5.4 => 3.5                   [Endpoint 1]
2021-07-03T20:12:38.745Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:12:38.746Z DRIVER « [Node 016] [REQ] [ApplicationCommand]
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      1
                                    │ destination: 0
                                    └─[MeterCCReport]
                                        type:        Electric
                                        scale:       W
                                        rate type:   Consumed
                                        value:       3.5
                                        time delta:  9 seconds
                                        prev. value: 5.4
2021-07-03T20:13:19.907Z SERIAL » 0x010e00131007600d00062501002560ff                                  (16 bytes)
2021-07-03T20:13:19.918Z DRIVER » [Node 016] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      96
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      0
                                    │ destination: 6
                                    └─[BinarySwitchCCSet]
                                        target value: false
2021-07-03T20:13:19.924Z SERIAL « [ACK]                                                                   (0x06)
2021-07-03T20:13:19.933Z SERIAL « 0x0104011301e8                                                       (6 bytes)
2021-07-03T20:13:19.935Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:13:19.939Z DRIVER « [RES] [SendData]
                                    was sent: true
2021-07-03T20:13:19.948Z SERIAL « 0x01050013600089                                                     (7 bytes)
2021-07-03T20:13:19.951Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:13:19.954Z DRIVER « [REQ] [SendData]
                                    callback id:     96
                                    transmit status: OK
2021-07-03T20:13:19.962Z CNTRLR   [Node 016] [~] [Binary Switch] currentValue: true => false        [Endpoint 6]
2021-07-03T20:13:20.968Z SERIAL » 0x010d00131006600d000625022561ff                                    (15 bytes)
2021-07-03T20:13:20.971Z DRIVER » [Node 016] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      97
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      0
                                    │ destination: 6
                                    └─[BinarySwitchCCGet]
2021-07-03T20:13:20.977Z SERIAL « [ACK]                                                                   (0x06)
2021-07-03T20:13:20.987Z SERIAL « 0x0104011301e8                                                       (6 bytes)
2021-07-03T20:13:20.990Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:13:21.001Z DRIVER « [RES] [SendData]
                                    was sent: true
2021-07-03T20:13:21.012Z SERIAL « 0x01050013610088                                                     (7 bytes)
2021-07-03T20:13:21.012Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:13:21.013Z DRIVER « [REQ] [SendData]
                                    callback id:     97
                                    transmit status: OK
2021-07-03T20:13:21.018Z SERIAL « 0x010d0004001007600d0600250300ac                                    (15 bytes)
2021-07-03T20:13:21.020Z CNTRLR   [Node 016] [~] [Binary Switch] currentValue: true => false        [Endpoint 0]
2021-07-03T20:13:21.022Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:13:21.024Z DRIVER « [Node 016] [REQ] [ApplicationCommand]
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      0
                                    │ destination: 0
                                    └─[BinarySwitchCCReport]
                                        current value: false
2021-07-03T20:13:21.029Z CNTRLR   [Node 016] Mapping unsolicited report from root device to first supporting end
                                  point #1
2021-07-03T20:13:21.032Z CNTRLR   [Node 016] [~] [Binary Switch] currentValue: true => false        [Endpoint 1]
2021-07-03T20:13:22.233Z SERIAL « 0x01180004001012600d01063202213400000000000900000219bc              (26 bytes)
2021-07-03T20:13:22.235Z CNTRLR   [Node 016] [~] [Meter] value[66049]: 53.6 => 0                    [Endpoint 6]
2021-07-03T20:13:22.236Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:13:22.238Z DRIVER « [Node 016] [REQ] [ApplicationCommand]
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      6
                                    │ destination: 0
                                    └─[MeterCCReport]
                                        type:        Electric
                                        scale:       W
                                        rate type:   Consumed
                                        value:       0
                                        time delta:  9 seconds
                                        prev. value: 53.7
2021-07-03T20:13:26.742Z SERIAL « 0x01180004001012600d010332022134000001810009000001a182              (26 bytes)
2021-07-03T20:13:26.747Z CNTRLR   [Node 016] [~] [Meter] value[66049]: 45.3 => 38.5                 [Endpoint 3]
2021-07-03T20:13:26.749Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:13:26.751Z DRIVER « [Node 016] [REQ] [ApplicationCommand]
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      3
                                    │ destination: 0
                                    └─[MeterCCReport]
                                        type:        Electric
                                        scale:       W
                                        rate type:   Consumed
                                        value:       38.5
                                        time delta:  9 seconds
                                        prev. value: 41.7
2021-07-03T20:13:31.024Z SERIAL » 0x010e00131007600d00032501002562f8                                  (16 bytes)
2021-07-03T20:13:31.028Z DRIVER » [Node 016] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      98
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      0
                                    │ destination: 3
                                    └─[BinarySwitchCCSet]
                                        target value: false
2021-07-03T20:13:31.032Z CNTRLR   [Node 016] Timed out while waiting for a response from the node
2021-07-03T20:13:31.037Z SERIAL « [ACK]                                                                   (0x06)
2021-07-03T20:13:31.043Z SERIAL « 0x0104011301e8                                                       (6 bytes)
2021-07-03T20:13:31.049Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:13:31.055Z DRIVER « [RES] [SendData]
                                    was sent: true
2021-07-03T20:13:31.058Z SERIAL « 0x0105001362008b                                                     (7 bytes)
2021-07-03T20:13:31.065Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:13:31.066Z DRIVER « [REQ] [SendData]
                                    callback id:     98
                                    transmit status: OK
2021-07-03T20:13:31.070Z CNTRLR   [Node 016] [~] [Binary Switch] currentValue: true => false        [Endpoint 3]
2021-07-03T20:13:32.079Z SERIAL » 0x010d00131006600d000325022563f8                                    (15 bytes)
2021-07-03T20:13:32.081Z DRIVER » [Node 016] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      99
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      0
                                    │ destination: 3
                                    └─[BinarySwitchCCGet]
2021-07-03T20:13:32.088Z SERIAL « [ACK]                                                                   (0x06)
2021-07-03T20:13:32.095Z SERIAL « 0x0104011301e8                                                       (6 bytes)
2021-07-03T20:13:32.097Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:13:32.100Z DRIVER « [RES] [SendData]
                                    was sent: true
2021-07-03T20:13:32.110Z SERIAL « 0x0105001363008a                                                     (7 bytes)
2021-07-03T20:13:32.112Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:13:32.114Z DRIVER « [REQ] [SendData]
                                    callback id:     99
                                    transmit status: OK
2021-07-03T20:13:32.122Z SERIAL « 0x010d0004001007600d0300250300a9                                    (15 bytes)
2021-07-03T20:13:32.123Z CNTRLR   [Node 016] [~] [Binary Switch] currentValue: false => false       [Endpoint 0]
2021-07-03T20:13:32.124Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:13:32.126Z DRIVER « [Node 016] [REQ] [ApplicationCommand]
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      0
                                    │ destination: 0
                                    └─[BinarySwitchCCReport]
                                        current value: false
2021-07-03T20:13:32.129Z CNTRLR   [Node 016] Mapping unsolicited report from root device to first supporting end
                                  point #1
2021-07-03T20:13:32.130Z CNTRLR   [Node 016] [~] [Binary Switch] currentValue: false => false       [Endpoint 1]
2021-07-03T20:13:35.732Z SERIAL « 0x01180004001012600d010332022134000000000009000001a102              (26 bytes)
2021-07-03T20:13:35.733Z CNTRLR   [Node 016] [~] [Meter] value[66049]: 38.5 => 0                    [Endpoint 3]
2021-07-03T20:13:35.735Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:13:35.737Z DRIVER « [Node 016] [REQ] [ApplicationCommand]
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      3
                                    │ destination: 0
                                    └─[MeterCCReport]
                                        type:        Electric
                                        scale:       W
                                        rate type:   Consumed
                                        value:       0
                                        time delta:  9 seconds
                                        prev. value: 41.7
2021-07-03T20:13:42.120Z CNTRLR   [Node 016] Timed out while waiting for a response from the node
2021-07-03T20:13:49.040Z SERIAL » 0x010e00131007600d00012501ff256403                                  (16 bytes)
2021-07-03T20:13:49.043Z DRIVER » [Node 016] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      100
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      0
                                    │ destination: 1
                                    └─[BinarySwitchCCSet]
                                        target value: true
2021-07-03T20:13:49.051Z SERIAL « [ACK]                                                                   (0x06)
2021-07-03T20:13:49.059Z SERIAL « 0x0104011301e8                                                       (6 bytes)
2021-07-03T20:13:49.061Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:13:49.064Z DRIVER « [RES] [SendData]
                                    was sent: true
2021-07-03T20:13:49.074Z SERIAL « 0x0105001364008d                                                     (7 bytes)
2021-07-03T20:13:49.076Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:13:49.079Z DRIVER « [REQ] [SendData]
                                    callback id:     100
                                    transmit status: OK
2021-07-03T20:13:49.085Z CNTRLR   [Node 016] [~] [Binary Switch] currentValue: false => true        [Endpoint 1]
2021-07-03T20:13:50.104Z SERIAL » 0x010d00131006600d000125022565fc                                    (15 bytes)
2021-07-03T20:13:50.105Z DRIVER » [Node 016] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      101
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      0
                                    │ destination: 1
                                    └─[BinarySwitchCCGet]
2021-07-03T20:13:50.116Z SERIAL « [ACK]                                                                   (0x06)
2021-07-03T20:13:50.122Z SERIAL « 0x0104011301e8                                                       (6 bytes)
2021-07-03T20:13:50.124Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:13:50.126Z DRIVER « [RES] [SendData]
                                    was sent: true
2021-07-03T20:13:50.143Z SERIAL « 0x0105001365008c                                                     (7 bytes)
2021-07-03T20:13:50.145Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:13:50.147Z DRIVER « [REQ] [SendData]
                                    callback id:     101
                                    transmit status: OK
2021-07-03T20:13:50.152Z SERIAL « 0x010d0004001007600d01002503ff54                                    (15 bytes)
2021-07-03T20:13:50.154Z CNTRLR   [Node 016] [~] [Binary Switch] currentValue: false => true        [Endpoint 0]
2021-07-03T20:13:50.156Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:13:50.160Z DRIVER « [Node 016] [REQ] [ApplicationCommand]
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      0
                                    │ destination: 0
                                    └─[BinarySwitchCCReport]
                                        current value: true
2021-07-03T20:13:50.164Z CNTRLR   [Node 016] Mapping unsolicited report from root device to first supporting end
                                  point #1
2021-07-03T20:13:50.166Z CNTRLR   [Node 016] [~] [Binary Switch] currentValue: true => true         [Endpoint 1]
2021-07-03T20:14:00.154Z SERIAL » 0x010e00131007600d00012501002566fe                                  (16 bytes)
2021-07-03T20:14:00.156Z DRIVER » [Node 016] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      102
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      0
                                    │ destination: 1
                                    └─[BinarySwitchCCSet]
                                        target value: false
2021-07-03T20:14:00.158Z CNTRLR   [Node 016] Timed out while waiting for a response from the node
2021-07-03T20:14:00.161Z SERIAL « [ACK]                                                                   (0x06)
2021-07-03T20:14:00.170Z SERIAL « 0x0104011301e8                                                       (6 bytes)
2021-07-03T20:14:00.172Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:14:00.174Z DRIVER « [RES] [SendData]
                                    was sent: true
2021-07-03T20:14:00.185Z SERIAL « 0x0105001366008f                                                     (7 bytes)
2021-07-03T20:14:00.186Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:14:00.188Z DRIVER « [REQ] [SendData]
                                    callback id:     102
                                    transmit status: OK
2021-07-03T20:14:00.192Z CNTRLR   [Node 016] [~] [Binary Switch] currentValue: true => false        [Endpoint 1]
2021-07-03T20:14:01.201Z SERIAL » 0x010d00131006600d000125022567fe                                    (15 bytes)
2021-07-03T20:14:01.204Z DRIVER » [Node 016] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      103
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      0
                                    │ destination: 1
                                    └─[BinarySwitchCCGet]
2021-07-03T20:14:01.212Z SERIAL « [ACK]                                                                   (0x06)
2021-07-03T20:14:01.219Z SERIAL « 0x0104011301e8                                                       (6 bytes)
2021-07-03T20:14:01.224Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:14:01.228Z DRIVER « [RES] [SendData]
                                    was sent: true
2021-07-03T20:14:01.237Z SERIAL « 0x0105001367008e                                                     (7 bytes)
2021-07-03T20:14:01.239Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:14:01.245Z DRIVER « [REQ] [SendData]
                                    callback id:     103
                                    transmit status: OK
2021-07-03T20:14:01.250Z SERIAL « 0x010d0004001007600d0100250300ab                                    (15 bytes)
2021-07-03T20:14:01.254Z CNTRLR   [Node 016] [~] [Binary Switch] currentValue: true => false        [Endpoint 0]
2021-07-03T20:14:01.257Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:14:01.264Z DRIVER « [Node 016] [REQ] [ApplicationCommand]
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      0
                                    │ destination: 0
                                    └─[BinarySwitchCCReport]
                                        current value: false
2021-07-03T20:14:01.272Z CNTRLR   [Node 016] Mapping unsolicited report from root device to first supporting end
                                  point #1
2021-07-03T20:14:01.273Z CNTRLR   [Node 016] [~] [Binary Switch] currentValue: false => false       [Endpoint 1]
2021-07-03T20:14:08.747Z SERIAL « 0x01180004001012600d01013202213400000000000900000000a0              (26 bytes)
2021-07-03T20:14:08.750Z CNTRLR   [Node 016] [~] [Meter] value[66049]: 3.5 => 0                     [Endpoint 1]
2021-07-03T20:14:08.750Z SERIAL » [ACK]                                                                   (0x06)
2021-07-03T20:14:08.752Z DRIVER « [Node 016] [REQ] [ApplicationCommand]
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      1
                                    │ destination: 0
                                    └─[MeterCCReport]
                                        type:        Electric
                                        scale:       W
                                        rate type:   Consumed
                                        value:       0
                                        time delta:  9 seconds
                                        prev. value: 0
2021-07-03T20:14:11.251Z CNTRLR   [Node 016] Timed out while waiting for a response from the node
```

**Comment by zucht** [comment] 2021-07-04 19:20
Experiencing exactly the same after updating  the Home Assistant Z-Wave JS Add-on to 0.1.28

**Comment by AlCalzone** [comment] 2021-07-04 20:53
Fixed on master in https://github.com/zwave-js/node-zwave-js/pull/2919
This is going into the next patch release of the driver.

The device is sending invalid multi channel commands, so we needed to add a workaround. The behavior before the update was also not correct btw.

**Comment by AlCalzone** [comment] 2021-07-04 20:54
Duplicate of #2917

**Closed as completed by AlCalzone** 2021-07-04 20:54 UTC
