### ISSUE TITLE
Implement message queued/dequeued events

### ISSUE THREAD

**Issue by marcus-j-davies** [zwave-js/zwave-js#1270] opened 2021-01-01 14:41 UTC
Happy new year to you all.

I'm not sure if this has any weight to it?
But I think 2 new controller events could provide some insurance for those with battery operated devices.

Whenever I am sending to a battery operated node or something that doesn't need to be a wake at that moment - whilst there is no reason to believe that they won't be delivered on their next wake up, I think it could add some value to some how flag that the message has been queued i.e a "**message queued**" event that they can subscribe to and subsequently a  "**message dequeued**" event.

The arguments for these events could be the id of the target node, the command class, and the time of the original message.

I think it removes the "is that going to be sent when they wake up" kind of doubt.
it could allow front end users of the lib to list pending messages in their apps.

**Comment by AlCalzone** [comment] 2021-01-01 16:32
Just to be sure I understand the use case correctly and clarify potential confusion:

> whilst there is no reason to believe that they won't be delivered on their next wake up

This is actually not guaranteed. Depending on the queue length and the responsiveness of the device/network, it could be that a queued message takes 2 or more wakeups to be delivered.

> I think it could add some value to some how flag that the message has been queued

Calling `node.setValue`, any CC API or `sendMessage/sendCommand` **will** queue at least one message. I don't see how we can add any value here.

> it could allow front end users of the lib to list pending messages in their apps.

**That** could be interesting however. I'm leaning towards adding this request to https://github.com/zwave-js/node-zwave-js/issues/985 (specifically the point "queue size")

**Comment by marcus-j-davies** [comment] 2021-01-01 16:43
> This is actually not guaranteed. Depending on the queue length and the responsiveness of the device/network, it could be that a queued message takes 2 or more wakeups to be delivered.

Got ya!

> Calling node.setValue, any CC API or sendMessage/sendCommand will queue at least one message. I don't see how we can add any value here.

Being advised that a message has been queued **due to a sleeping node**, feels as if it could add some closure, on the users request, certainly for those who are new to the ZWave protocol, and looking to get into home automation.

None sleeping nodes will, most of the time, show the affect of the command moments after, sleeping nodes however, you are left to trust everything that you can't see. being advised as to why something hasn't happened (specifically queueing due to sleep status) could, again add closure

> That could be interesting however. I'm leaning towards adding this request to #985 (specifically the point "queue size")

if one could somehow get a sense of what the queue contains - that should provide all the benefits, and will allow for some UI's that present what is waiting to be done on the network.

**Comment by AlCalzone** [comment] 2021-01-01 23:13
Transparency is a good thing and I would really like to give users tools to understand what is happening. 

I've added your suggestion to the other issue, so I'm going to mark this one as a...

**Comment by AlCalzone** [comment] 2021-01-01 23:13
Duplicate of #985

**Closed as completed** 2021-01-01 23:13 UTC
Labels: enhancement

**Comment by LordMike** [comment] 2021-01-10 16:42
Bonus to having events per message, rather than just counters, is also being able to see how long it actually took to deliver that "turn on" message. Would help immensely in tracking down where delays are occurring, when lights appear slow.

**Comment by AlCalzone** [comment] 2021-01-10 17:27
Further discussion in #985 please
