### ISSUE TITLE
Lock fails to report status when unlocked with keypad

### ISSUE THREAD

**Issue by prwood80** [zwave-js/zwave-js#1632] opened 2021-02-06 22:50 UTC
First - thanks for all the hard work.  I've spent some time digging into this, but I haven't found anyone else with this issue.  Hopefully I didn't miss something.

Issue: I have a Yale Lock (YRD226 - which identifies as YRD256 - which I believe is equivalent per Yale documentation).  When I enter a passcode at the deadbolt, my status is not reflec[Yale zwave integration guide](https://www.google.com/url?sa=t&source=web&rct=j&url=https://products.z-wavealliance.org/ProductManual/File%3Ffolder%3D%26filename%3DMarketCertificationFiles/3211/YaleRealLivingAssureSL_Z-WavePlus_SystemIntegratorsGuide.pdf&ved=2ahUKEwjAtY6M1dfuAhVWBc0KHcv5BhcQFjANegQIFRAB&usg=AOvVaw21ZMPsTnJ_oGD0ZYgbA4s5) [Yale zwave integration guide](https://www.google.com/url?sa=t&source=web&rct=j&url=https://products.z-wavealliance.org/ProductManual/File%3Ffolder%3D%26filename%3DMarketCertificationFiles/3211/YaleRealLivingAssureSL_Z-WavePlus_SystemIntegratorsGuide.pdf&ved=2ahUKEwjAtY6M1dfuAhVWBc0KHcv5BhcQFjANegQIFRAB&usg=AOvVaw21ZMPsTnJ_oGD0ZYgbA4s5) ted (doesn't make it to zwavejs2mqtt).  If I manually use the deadbolt (inside knob), it reports both lock and unlock status.  I believe the relevant error in the zwavejs log is: 

> 16:16:38.501 DRIVER   Could not assemble partial CCs because the payload is invalid. Dropping them.

The node in question is 11.  If you start at the bottom of the log, and search [Node 011], you'll see the last message received by the driver related to the unlock with a user code event (time: 16:16:38.444).  Other relevant events (stepping in reverse) would be a manual lock (time: 16:16:31.867) and a manual unlock (time: 16:16:26.386).

Attached are logs.  Sorry, I tried to set the environment variable with my docker container, and restarted, but it appears to have all my devices logged.

Any thoughts?

**Comment by towerhand** [comment] 2021-02-06 22:56
Probably related to #1602

**Comment by prwood80** [comment] 2021-02-06 23:10
Possibly, though, I was aware of that issue.  I also have a BE469 (both manual and keypad notifications are working, but I had to implement a work around for some of the status by using the zwave_js_event in home assistant).  The difference was that zwavejs driver was at least processing the zwave message.  In this case, it appears the the message doesn't make it beyond the zwavejs driver, so I'm unable to effectively work around the dropped message.

**Comment by AlCalzone** [comment] 2021-02-06 23:13
For the invalid payload I need your network key. You can send that to the email in my profile

**Comment by prwood80** [comment] 2021-02-06 23:21
@AlCalzone Key sent to your email.  Thanks

**Comment by AlCalzone** [comment] 2021-02-07 10:53
@prwood80 the device sends an invalid UserCode Report, which is being dropped by zwave-js. According to the specs, it must look like this:
![grafik](https://user-images.githubusercontent.com/17641229/107144240-34d00600-693a-11eb-97d5-fb29940923aa.png)
The intent of that command is to report the status **and** code for a given user code ID.

The one sent by your device does not contain any bytes for the user code, so it is basically misusing the User Code CC for notifications.

While it is theoretically possible to treat this as a notification, based on the above report we don't know if that is a lock or unlock operation and there is no notification for "user code entered".

**Comment by prwood80** [comment] 2021-02-07 11:34
Thanks for checking that. I guess I'm unsure how this works with my two prior controllers (smart things, then built in zwave with home assistant). I thought this was going to be a notification cc that was dropped. This device should report lock status and user code index using the notification alarm type and alarm level according to this document:
https://www.google.com/url?sa=t&source=web&rct=j&url=https://products.z-wavealliance.org/ProductManual/File%3Ffolder%3D%26filename%3DMarketCertificationFiles/3211/YaleRealLivingAssureSL_Z-WavePlus_SystemIntegratorsGuide.pdf&ved=2ahUKEwjAtY6M1dfuAhVWBc0KHcv5BhcQFjANegQIFRAB&usg=AOvVaw21ZMPsTnJ_oGD0ZYgbA4s5

**Comment by Ikcelaks** [comment] 2021-02-07 16:23
The HA legacy zwave-js integration inferred the lock status for the Yale YRD256 (and many other Yale locks) from the alarm_type.

**Comment by prwood80** [comment] 2021-02-07 16:31
@Ikcelaks This is probably a dumb question, but I don't seem to be getting the alarm type (as it seemed to come across in other integrations).  I've also monitored the status with MQTT explorer (states don't seem to update their either).  Am I overlooking something obvious or is the alarm_type not fully supported yet?  It was my basic understanding that the alarm type & code would come across in the Notification message upon a deadbolt action.

**Comment by AlCalzone** [comment] 2021-02-07 16:32
I took a look at the log again. It seems that we do get two Notification reports (one for lock, one for unlock) around the time where the user code report comes.
So basically, this is a duplicate of #1602. I don't think I can realistically do anything about the invalid user code report. So you won't know which user ID unlocked the door.

**Comment by prwood80** [comment] 2021-02-07 16:51
The sequence of events were:
* Manual unlock (time: 16:16:26.386, which was me unlocking from the inside of the house to open the door, notification message received and processed)
* Manual lock (time: 16:16:31.867, which was me locking the door while it was open so that I could then unlock with the keypad, notification message received and processed)
* At time=16:16:38.432, I had initiated an unlock using the keypad with a passcode entry.  This results in the CC payload issue, but no notification messages.  Because of this, nothing seems to change in the zwavejs web gui and no state change is reported over MQTT or to Home Assistant.

In other words, there should have been 3 notification reports, not 2.

Is it possible the user code report you noted above also has an unprocessed notification report CC in the security encapsulation CC?  It looks like multiple commands can be packed in the security message.  If the whole message is dropped, maybe the notification is dropped because of the malformed user code message?  I was trying to use Z-Wave controller to decode the security CC message, but I don't think I was using the right combination of Nonce internal & external (I see the nonce from zwavejs, the IV in the message from the deadbolt, and my local network key).   What tool do you use to decode the packed message?

**Comment by AlCalzone** [comment] 2021-02-07 17:01
> Is it possible the user code report you noted above also has an unprocessed notification report CC in the security encapsulation CC?

Let me check that.

Btw, to decode I edit the file `test/debug.js`, enter the data, nonce (the one we sent just before) and network key in lines 24ff and run the "Decode Message" debug task in VSCode

**Comment by AlCalzone** [comment] 2021-02-07 17:06
Okay - you were onto something... That IS a notification CC with an embedded (but shortened) User Code Report. I though I already had a workaround for that.

**Comment by prwood80** [comment] 2021-02-07 17:10
That's good to hear. I'd be glad to test if you want me to try something, but my use right now is limited to a docker container on a raspberry pi. 

Thanks so much for your time looking at this.

**Comment by AlCalzone** [comment] 2021-02-07 17:23
If you like, you can build a new container against the branch from #1640.
But since the manual test panned out, I'm probably going to merge this quickly.

**Comment by towerhand** [comment] 2021-02-07 18:53
> That's good to hear. I'd be glad to test if you want me to try something, but my use right now is limited to a docker container on a raspberry pi.
> 
> Thanks so much for your time looking at this.

Are you using zjs2m? if so, here you go: https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/docker_custom_builds

I'm using this command to build mine right now on my rpi3b, takes a while but it works.
DOCKER_BUILDKIT=1 docker build --build-arg SRC=git-clone-src --build-arg Z2M_BRANCH=improved-mesh-graph --build-arg ZWJ_BRANCH=map-notification-lock --no-cache -f zwavejs2mqtt/docker/Dockerfile.contrib -t zwavejs2mqtt .

In your case, you might want to use the "notification-truncated-usercode-report" branch.

**Comment by prwood80** [comment] 2021-02-07 19:00
I am using zjs2m. Thanks for this info. It's very helpful!

**Comment by AlCalzone** [comment] 2021-02-07 21:14
2nd part (missing lock status update) is done in #1641

**Closed as completed** 2021-02-07 21:49 UTC
Labels: bug

**Comment by prwood80** [comment] 2021-02-07 23:53
Built and ran locally with the changes and all is working. Thanks

**Comment by Quixote1** [comment] 2022-02-14 01:44
Sorry for drudging up an old thread, but I seem to be having a similar issue with my Yale YRD256 and Zwavejs2mqtt. The lock operates as it should, and even toggles between the available commands of "Lock" and "Unlock" on its Lovelace card in Home Assistant, but the status has shown "Open" since my install a couple of weeks ago. Everything is reasonably up-to-date, though I'm starting to wonder if there may be a firmware update for the lock.  Is there something that I may have failed to configure?  Thanks.

**Comment by AlCalzone** [comment] 2022-02-14 10:38
> in Home Assistant, but the status has shown "Open" since my install a couple of weeks ago

Please report this in https://github.com/home-assistant/core so the devs can figure out if this is an issue in HA or not.

**Comment by Quixote1** [comment] 2022-02-14 17:06
Will do. Thanks
