### ISSUE TITLE
Erratic KWh report NAS-WR01ZE powerplug

### ISSUE THREAD

**Issue by JasperPlant** [zwave-js/zwave-js#3235] opened 2021-08-25 12:52 UTC
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
I am not sure if this is a firmware issue or an issue with Z-Wave JS

What do you observe?
The KWH output of the MeterCCReport of the Neo Coolcam NAS-WR01ZE is erratic. 
it switches between the correct value and a value that is around -20,000,000

What did you expect to happen?
a consistent report of KWh used over the lifetime of the plug.

  2. Click on '...'
  3. Scroll down to '...'

### Device information

Manufacturer: Neo
Model name: Coolcam NAS-WR01ZE Powerplug
Node ID in your network: 
006 and 007

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 0.1.37
`Home Assistant` branch: 2021.8.8
`z-wave integration` driver: 8.1.1 server: 1.10.0
`zwavejs2mqtt` branch:

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

wrong value:
```
2021-08-25T12:33:16.449Z SERIAL « 0x0114000400070e32022144800001fb012d800001fb9f                      (22 bytes)
2021-08-25T12:33:16.454Z CNTRLR   [Node 007] [~] [Meter] value[65537]: -21474831.41 => -21474831.41 [Endpoint 0]
2021-08-25T12:33:16.458Z SERIAL » [ACK]                                                                   (0x06)
2021-08-25T12:33:16.463Z DRIVER « [Node 007] [REQ] [ApplicationCommand]
                                  └─[MeterCCReport]
                                      type:        Electric
                                      scale:       kWh
                                      rate type:   Consumed
                                      value:       -21474831.41
                                      time delta:  301 seconds
                                      prev. value: -21474831.41
```

right value:
```
2021-08-25T12:43:16.550Z SERIAL « 0x0114000400070e32022144000001fe012d000001fe9f                      (22 bytes)
2021-08-25T12:43:16.554Z CNTRLR   [Node 007] [~] [Meter] value[65537]: 5.1 => 5.1                   [Endpoint 0]
2021-08-25T12:43:16.558Z SERIAL » [ACK]                                                                   (0x06)
2021-08-25T12:43:16.563Z DRIVER « [Node 007] [REQ] [ApplicationCommand]
                                  └─[MeterCCReport]
                                      type:        Electric
                                      scale:       kWh
                                      rate type:   Consumed
                                      value:       5.1
                                      time delta:  301 seconds
                                      prev. value: 5.1
```

**Comment by AlCalzone** [comment] 2021-08-25 13:54
Duplicate of #2692

**Closed as completed by AlCalzone** 2021-08-25 13:54 UTC
Labels: cannot fix ❌
