### ISSUE TITLE
LZW30-SN unable to view correct or change local protection via zwavejs or zwavejs2mqtt

### ISSUE THREAD

**Issue by nmsousa76** [zwave-js/zwave-js#3252] opened 2021-08-27 16:15 UTC
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

YES, BUT a Home Assistant developer has told me to come here

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

Unable to change the local protection settings for LZW30-SN (all other Models of Inovelli seem to be fine). All values are showing up as unknown and are unable to be defined.  The below Screenshot is from zwavejs2mqtt only because Config settings in zwavejs do not illustrate it.   That said, teh results are exactly the same in zwaveJS

![image](https://user-images.githubusercontent.com/65356035/131155639-a933dbf8-7347-4e3a-b74c-a31902d1a3aa.png)

Based on a thread with the hass core team (https://github.com/home-assistant/core/issues/55305), the values I should be expecting are 0x0,0x1 and 0x2 and as you can see from the screenshot or the below logs at the end of thread that I pulled out of the zwavejs addon, i am getting 0x08, 0x09, 0x0a.

Another thing to note is that I went back to openzwave to see if the issue was present there and it was not.   So i don't believe this is a device issue.  

![image](https://user-images.githubusercontent.com/65356035/131156421-df33ace6-7746-4d3d-b7bc-f3319131b16c.png)

Other things to note, this this behavior is also exhibited in LZW31-SN, but not in LZW36.

[Logs]
2021-08-27T15:49:42.809Z SERIAL » 0x0109001311025b0125931a (11 bytes)
2021-08-27T15:49:42.809Z DRIVER » [Node 017] [REQ] [SendData]
│ transmit options: 0x25
│ callback id: 147
└─[CentralSceneCCSupportedGet]
2021-08-27T15:49:42.813Z SERIAL « [ACK] (0x06)
2021-08-27T15:49:42.816Z SERIAL « 0x0104011301e8 (6 bytes)
2021-08-27T15:49:42.816Z SERIAL » [ACK] (0x06)
2021-08-27T15:49:42.817Z DRIVER « [RES] [SendData]
was sent: true
2021-08-27T15:49:42.831Z SERIAL « 0x0105001393007a (7 bytes)
2021-08-27T15:49:42.832Z SERIAL » [ACK] (0x06)
2021-08-27T15:49:42.832Z DRIVER « [REQ] [SendData]
callback id: 147
transmit status: OK
2021-08-27T15:49:52.839Z CNTRLR [Node 017] Timed out while waiting for a response from the node
2021-08-27T15:49:52.840Z CNTRLR [Node 017] Querying supported scenes timed out, skipping interview...
2021-08-27T15:49:52.844Z CNTRLR [Node 017] Interviewing Protection...
2021-08-27T15:49:52.844Z CNTRLR » [Node 017] querying protection capabilities...
2021-08-27T15:49:52.851Z SERIAL » 0x0109001311027504259436 (11 bytes)
2021-08-27T15:49:52.852Z DRIVER » [Node 017] [REQ] [SendData]
│ transmit options: 0x25
│ callback id: 148
└─[ProtectionCCSupportedGet]
2021-08-27T15:49:52.880Z SERIAL « [ACK] (0x06)
2021-08-27T15:49:52.882Z SERIAL « 0x0104011301e8 (6 bytes)
2021-08-27T15:49:52.883Z SERIAL » [ACK] (0x06)
2021-08-27T15:49:52.884Z DRIVER « [RES] [SendData]
was sent: true
2021-08-27T15:49:52.899Z SERIAL « 0x0105001394007d (7 bytes)
2021-08-27T15:49:52.899Z SERIAL » [ACK] (0x06)
2021-08-27T15:49:52.900Z DRIVER « [REQ] [SendData]
callback id: 148
transmit status: OK
2021-08-27T15:49:52.914Z SERIAL « 0x010d00040011077505000007000790 (15 bytes)
2021-08-27T15:49:52.916Z CNTRLR [Node 017] [+] [Protection] supportsExclusiveControl: [Endpoint 0] [internal]
false
2021-08-27T15:49:52.917Z CNTRLR [Node 017] [+] [Protection] supportsTimeout: false [Endpoint 0] [internal]
2021-08-27T15:49:52.917Z CNTRLR [Node 017] [+] [Protection] supportedLocalStates: 8,9, [Endpoint 0] [internal]
10
2021-08-27T15:49:52.918Z CNTRLR [Node 017] [+] [Protection] supportedRFStates: 8,9,10 [Endpoint 0] [internal]
2021-08-27T15:49:52.918Z CNTRLR [Node 017] [Protection] local: metadata updated [Endpoint 0]
2021-08-27T15:49:52.919Z CNTRLR [Node 017] [Protection] rf: metadata updated [Endpoint 0]
2021-08-27T15:49:52.920Z SERIAL » [ACK] (0x06)
2021-08-27T15:49:52.922Z DRIVER « [Node 017] [REQ] [ApplicationCommand]
└─[ProtectionCCSupportedReport]
supports exclusive control: false
supports timeout: false
local protection states:
· unknown (0x08)
· unknown (0x09)
· unknown (0x0a)
RF protection states:
· unknown (0x08)
· unknown (0x09)
· unknown (0x0a)
2021-08-27T15:49:52.925Z CNTRLR « [Node 017] received protection capabilities:
exclusive control: false
timeout: false
local protection states:
· unknown (0x08)
· unknown (0x09)
· unknown (0x0a)
RF protection states:
· unknown (0x08)
· unknown (0x09)
· unknown (0x0a)
2021-08-27T15:49:52.926Z CNTRLR » [Node 017] querying protection status...
2021-08-27T15:49:52.933Z SERIAL » 0x0109001311027502259531 (11 bytes)
2021-08-27T15:49:52.934Z DRIVER » [Node 017] [REQ] [SendData]
│ transmit options: 0x25
│ callback id: 149
└─[ProtectionCCGet]
2021-08-27T15:49:52.937Z SERIAL « [ACK] (0x06)
2021-08-27T15:49:52.940Z SERIAL « 0x0104011301e8 (6 bytes)
2021-08-27T15:49:52.941Z SERIAL » [ACK] (0x06)
2021-08-27T15:49:52.942Z DRIVER « [RES] [SendData]
was sent: true
2021-08-27T15:49:52.956Z SERIAL « 0x0105001395007c (7 bytes)
2021-08-27T15:49:52.956Z SERIAL » [ACK] (0x06)
2021-08-27T15:49:52.957Z DRIVER « [REQ] [SendData]
callback id: 149
transmit status: OK
2021-08-27T15:49:52.973Z SERIAL « 0x010a00040011047503000092 (12 bytes)
2021-08-27T15:49:52.974Z CNTRLR [Node 017] [+] [Protection] local: 0 [Endpoint 0]
2021-08-27T15:49:52.974Z CNTRLR [Node 017] [+] [Protection] rf: 0 [Endpoint 0]
2021-08-27T15:49:52.975Z SERIAL » [ACK] (0x06)
2021-08-27T15:49:52.976Z DRIVER « [Node 017] [REQ] [ApplicationCommand]
└─[ProtectionCCReport]
local: Unprotected
rf: Unprotected
2021-08-27T15:49:52.978Z CNTRLR « [Node 017] received protection status:
local: Unprotected
rf Unprotected
2021-08-27T15:49:52.978Z CNTRLR [Node 017] [+] [Protection] interviewComplete: true [Endpoint 0] [internal]
2021-08-27T15:49:52.979Z CNTRLR [Node 017] Interview stage completed: CommandClasses
2021-08-27T15:49:52.980Z CNTRLR [Node 017] Interview stage completed: OverwriteConfig
2021-08-27T15:49:52.980Z CNTRLR [Node 017] Interview completed
2021-08-27T15:49:52.981Z CNTRLR [Node 017] The node is ready to be used

### Device information

Manufacturer:  Inovelli
Model name:  lzw30-sn
Node ID in your network: 17

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch:  0.1.37 
`zwavejs2mqtt` branch:

### Did you change anything?

no

### If yes, what did you change?

This has been the behavior ever since i migrated to zwavejs from openzwave.   This has also been validated on various hass setups.   (production and clean new install

### Did this work before?

No, it never worked anywhere

### If yes, where did it work?

As satted aboved, never worked in zwaveJS or zwavejs2mqtt but did work fine on open zwave

### Attach Driver Logfile

[zwave_js (1).log](https://github.com/zwave-js/node-zwave-js/files/7068289/zwave_js.1.log)

**Comment by AlCalzone** [comment] 2021-08-28 09:31
This is a bug in the device firmware. We have an issue somewhere, but I cannot find it. The problem is that the device incorrectly encodes the possible protection states in the `ProtectionCCSupportedReport`.

**Comment by nmsousa76** [comment] 2021-08-28 14:04
Will upgrading the device firmware help?

**Comment by AlCalzone** [comment] 2021-08-28 14:08
It might - the Innovelli support should be able to answer that.

**Comment by nmsousa76** [comment] 2021-08-28 15:02
i upgraded to 1.22 and the issue still exists.  I saw you added a tag of "cannot fix".   Are you saying there is no option here?

**Comment by nmsousa76** [comment] 2021-08-28 16:22
Just a slight correction to one of my previous posts, LZW31-SN is working as expected, so only LZW30-SN models seem to be broken is broken.  ()

**Comment by blhoward2** [comment] 2021-08-28 20:59
I sent Inovelli support a message on this.

**Comment by nmsousa76** [comment] 2021-08-28 21:52
I opened a support ticket as well oninovelli https://support.inovelli.com/portal/en/ticket/407409000033235320

**Comment by blhoward2** [comment] 2021-08-31 19:20
From Inovelli: "This is an issue that has been reported to our manufacturer. I’m not sure on when a fix will be released, but it’s been confirmed an issue on our end."

**Closed as completed** 2021-09-04 00:11 UTC
Labels: cannot fix ❌

**Comment by josh-m-sharpe** [comment] 2022-10-18 21:09
Ok so I might be experiencing a similar issue where my switches become locally inoperable.  I too upgraded from ozwdaemon to zwavejs2mqtt and now to zwave-js-ui.

Question for the group:  if ozwdaemon didn't have this problem, how is this a "cannot fix" for zwave-js?  Seems to me that ozwdaemon was doing something to not brick the devices that zwave-js is doing EVEN IF there's a hardware bug.

Maybe?

**Comment by blhoward2** [comment] 2022-10-18 23:46
First of all, your description doesn’t sound like this bug, so I’m not sure this is what you have going on. 

Secondly, OZW infamously included device specific workarounds within their code base, essentially changing the expected functionality for one off devices to correct manufacturer errors. This was part of the reason their code was bloated and buggy. We’ve declined to do the same, so some misbehaving devices simply won’t work until the manufacturer fixes them. The driver is written to the zwave spec everyone is supposed to be following. 

We make minor allowances for compact flags where something can just be turned off, but we’re not going to refactor functions to be specific to certain devices.

**Comment by kpine** [comment] 2022-10-19 06:20
> Ok so I might be experiencing a similar issue where my switches become locally inoperable. I too upgraded from ozwdaemon to zwavejs2mqtt and now to zwave-js-ui.

@josh-m-sharpe I don't think Z-Wave JS will let you set a protected mode at all for these devices, which is the problem defined here. Nevertheless, if you think your switches are protected, you should be able to set them to unprotected by using the CC API for the [Protection CC](https://zwave-js.github.io/node-zwave-js/#/api/CCs/Protection). In Home Assistant, use this service call in the Services Dev Tools and choose your device or entity to apply it to (hint: switch to YAML mode, paste this then go back to UI mode):

```yaml
service: zwave_js.invoke_cc_api
data:
  command_class: "117"
  method_name: set
  parameters:
    - 0
```

If you're not using HA and only Z-Wave JS UI, you can convert the above to a [driver function](https://zwave-js.github.io/zwave-js-ui/#/usage/driver_function). If you're not sure how to do so, feel free to ask.

> Question for the group: if ozwdaemon didn't have this problem, how is this a "cannot fix" for zwave-js? Seems to me that ozwdaemon was doing something to not brick the devices that zwave-js is doing EVEN IF there's a hardware bug.

This problem arises because Z-Wave JS supports up to v2 of the Protection CC, which added the ability to query the device for its supported protection modes. In this case, the Inovelli also supports v2 and returns bad values (bytes are swapped) for the supported modes. OZW only implements Protection CC v1 (I wrote about this in the [linked issue](https://github.com/home-assistant/core/issues/55305#issuecomment-907328575)), which doesn't have the ability to ask for supported modes, thus it's immune to this issue (but also doesn't support RF protection). It simply uses the fixed values for local protection defined by the CC specification.

EDIT: dug up [this thread](https://community.inovelli.com/t/lzw30-sn-how-to-disable-relay-without-smartthings/8051/14) from the Inovelli community which has some familiar names and explains it all. The linked comment says you can press the config button 8-times to enable or disable protection, so you don't any software functionality if you've accidentally enabled it.

**Comment by josh-m-sharpe** [comment] 2022-10-19 13:44
Thanks so much for the response/feedback!  I will test the service call and the 8 button presses the next time this happens.
