### ISSUE TITLE
[question] Is it expected that device status does not persist between reboots?

### ISSUE THREAD

**Issue by michaelolson** [zwave-js/zwave-js#2644] opened 2021-05-13 21:54 UTC
I'm using `zwavejs2mqtt` through Docker. I have a problem that, when I bring the image down and back up, several devices, inconsistently, have to be manually refreshed. Before reboot, all devices have a date in the `Last Active` column and report appropriate capabilities.

After reboot, some devices, which includes mains connected devices, report `Never` as the `Last Active` time and lose their capabilities. For a particular device, before reboot and after a manual `RefreshValues`, the capabilities are:
```
Values
Multilevel Switch >
Central Scene >
Manufacturer Specific >
Version >
```

After reboot, the entire `Values` section disappears until manually refreshed, meaning that the device stops working entirely. This has resulted in me calling `RefreshValues` on most nodes after reboot in order to get back to a stable system.

I'm considering writing an integration that detects missing values and automatically calls `RefreshValues`, but I'm wondering if there's a way to avoid needing this.

**Comment by AlCalzone** [comment] 2021-05-23 21:25
@michaelolson Judging from your files, it doesn't look like the cache is actually corrupted. 

It seems more like the stick is having some troubles, causing the serial communication to mess up, which likely causes the unknown status in the UI.
Your log is full of these:
```
2021-05-19T17:13:19.137Z CNTRLR   No response from controller after 1/3 attempts. Scheduling next try in 100 ms.
...
2021-05-19T17:13:20.252Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
...
2021-05-19T17:13:22.398Z CNTRLR   [Node 003] ping failed: Timeout while waiting for an ACK from the controller
```

**Comment by michaelolson** [comment] 2021-05-26 18:59
Hrmm, interesting. I'm not sure what that means for my controller. Have you seen behavior like that before? Would the only fix be to replace the controller?

A point I'm confused on is if the poor behavior is timeouts contacting the controller, wouldn't the data in the console still fall back to what's in the cache if it can't get a response from the controller? What causes the data to end up empty instead of using the valid values in the cache?

**Comment by AlCalzone** [comment] 2021-05-26 19:33
We're pretty sure now that this has to do with zwavejs2mqtt querying all neighbors immediately when the driver starts. This seems to cause older sticks to trip up.

Normally during the startup, listening nodes are pinged to figure out if they are alive or dead, then they are marked "ready". zwavejs2mqtt uses this event to display the information we already know, but that doesn't happen if the stick gets stuck before that.

**Comment by AlCalzone** [comment] 2021-05-26 19:36
This should be fixed by https://github.com/zwave-js/zwavejs2mqtt/pull/1279 btw, which was merged a couple of hours ago

**Closed as completed by AlCalzone** 2021-05-26 19:36 UTC

**Comment by michaelolson** [comment] 2021-05-26 19:38
Ahh, got it. So some kind of throttling of requests for older sticks would let the process succeed and having a fallback to display the information even if the ping fails guarantees it doesn't end up empty. Thanks for linking in the fix.

**Comment by AlCalzone** [comment] 2021-05-26 19:42
Its not throttling the requests per se, its mixing requests that read from the external NVM and requests that use the radio and potentially write to the NVM. I can't reproduce that on my Z-Wave 700 stick no matter how hard I try, but older devices **really** don't like that.

**Comment by michaelolson** [comment] 2021-05-26 20:54
Thanks for the clarification, I appreciate the detail. That also seems to constitute a recommendation for the Z-Wave 700 if I ever need a replacement.
