### ISSUE TITLE
Refresh Configuration CC values on load if the device config Configuration info has changed

### ISSUE THREAD

**Issue by raman325** [zwave-js/zwave-js#3166] opened 2021-08-08 23:51 UTC
**Is your feature request related to a problem? Please describe.**
A user reported an issue here: https://github.com/home-assistant/core/issues/54181 related to an out of date config file. They had updated to a version of zwave-js that had the fixed config file, but the state of the Configuration CC must have been cached from previously. We asked them to do a re-interview (really a refreshCCValues would have done it) and that resolved the problem.

**Describe the solution you'd like**
It seems to me like there should be a better way to handle this that doesn't require user intervention. The solution I suggested in the summary may not be the best one, but it does express the intent I am trying to get to.

**Describe alternatives you've considered**
Re-interview or refresh CC values will do it but requires user intervention.

**Additional context**
Add any other context or screenshots about the feature request here. If you want to propose an API, share your thoughts how it could be used (syntax).

**Comment by AlCalzone** [comment] 2021-08-09 07:35
We've discussed similar things in the past. Some config file changes require a re-interview for the changes to be applied, but I'm opposed to doing that automatically. Worst case something goes wrong while the user has no chance to intervene. If someone has built an automation that controls a door lock, potentially breaking that could be really bad.

What I could imagine is some kind of status that notifies the user that re-interviewing might be necessary.

**Comment by AlCalzone** [comment] 2021-08-09 07:35
Duplicate of #2909

**Closed as completed** 2021-08-09 07:35 UTC
Labels: enhancement
