### ISSUE TITLE
ManufacturerSpecificCC not finished on node ready

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwave-js#1501] opened 2021-01-26 13:09 UTC
`node ready` event is triggered without the `deviceConfig`, seems that the `ManufacturerSpecificCCReport` comes after the event 

Ref: https://github.com/zwave-js/zwavejs2mqtt/issues/347

**Comment by AlCalzone** [comment] 2021-01-26 14:31
That is caused by multiple concurrent interviews (where starting one deletes the info received by another one). Can't do anything until I've overhauled the interview process (if it still happens then)

**Comment by robertsLando** [comment] 2021-01-26 14:36
@AlCalzone Could we change the title to `Multuple concurrent interview of the same node` ?

**Comment by AlCalzone** [comment] 2021-01-26 14:41
If you like. I don't think it makes much sense to have multiple issues for the same thing though.
==> #903, #900

**Comment by robertsLando** [comment] 2021-01-26 14:50
Humm ok so what? Closing as dup?

**Comment by AlCalzone** [comment] 2021-01-26 14:56
Duplicate of #903

**Closed as completed by AlCalzone** 2021-01-26 14:56 UTC
Labels: wontfix
