### ISSUE TITLE
Lock jammed status not updating.

### ISSUE THREAD

**Issue by warllo54** [zwave-js/zwave-js#2856] opened 2021-06-14 20:49 UTC
**Checklist:**

-   [x] My problem is **not** within Home Assistant or the ZWave JS integration. **Or:** a Home Assistant developer has told me to come here.
-   [x] My problem is **not** within ZWaveJS2MQTT. **Or:** a ZWaveJS2MQTT developer has told me to come here.
-   [x] I have checked the troubleshooting section and my problem is **not** described there.
-   [x] I have read the changelog and my problem was **not** mentioned there.

[22-113-0-Access Control-Lock state] Lock state [11] Lock jammed <------- this value will not update, when first setting up the device or re-interviewing the locked jam will be clear, once it's triggered it's stuck on Lock jammed.

A clear and concise description of what the bug is. Describe what causes the bug, what you observe, and what happens as a result.

**Device information**

Which device(s) is/are affected (manufacturer/model)? BE469ZP 
What is/are the node IDs?
Node 22

**Did you change anything?**

-   [ ] **Yes**: _(please describe)_
-   [x] **No**

**Did this use to work before?**

-   [ ] **Don't know**, this is a new device
-   [x] **No**, it never worked anywhere
-   [ ] **Yes**, in: _(specify application with versions)_

**How are you using `node-zwave-js`**

-   [x] `zwavejs2mqtt` (latest) docker image
-   [ ] `zwavejs2mqtt` (dev) docker image
-   [ ] `zwavejs2mqtt` Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] ioBroker.zwave2 adapter
-   [ ] `HomeAssistant` version XYZ
-   [ ] Pkg
-   [ ] Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] `node-red-contrib-zwave-js`
    -   Module version (double click node): 
-   [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github))
-   [ ] Other: 

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Additional context**

**Logfile:**

[zwavejs_2021-06-14.log](https://github.com/zwave-js/node-zwave-js/files/6651198/zwavejs_2021-06-14.log)

**Comment by AlCalzone** [comment] 2021-06-14 21:06
There's no interaction with the lock included in the logfile. Nonetheless, I think this is a duplicate of #1543

**Closed as completed** 2021-06-14 21:07 UTC
